[package]
name = "operators"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[features]
default = ["common-cpu", "nvidia-gpu", "cambricon-mlu", "ascend-card"]
common-cpu = ["dev-mempool/common-cpu", "gemm"]
nvidia-gpu = ["dev-mempool/nvidia-gpu", "cublas", "nccl", "libloading"]
cambricon-mlu = ["cndrv", "cnnl"]
ascend-card = ["ascendcl"]

[dependencies]
dev-mempool.workspace = true
digit-layout.workspace = true
ndarray-layout = { git = "https://github.com/YdrMaster/ndarray-layout", rev = "3de35cc" }
rayon = "1.10"
lru = "0.12"
half = "2.4"
log = "0.4"

gemm = { version = "0.18", optional = true }

cublas = { workspace = true, optional = true }
nccl = { workspace = true, optional = true }
libloading = { version = "0.8", optional = true }

cndrv = { workspace = true, optional = true }
cnnl = { workspace = true, optional = true }

ascendcl = { workspace = true, optional = true }

[build-dependencies]
build-script-cfg.workspace = true
search-cuda-tools.workspace = true
search-neuware-tools.workspace = true
search-ascend-tools.workspace = true

[dev-dependencies]
dev-mempool = { workspace = true, features = ["common-cpu"] }
gemm = "0.18"
rand = "0.8"
