[package]
name = "operators"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[features]
default = ["common-cpu", "nvidia-gpu", "cambricon-mlu", "ascend-card"]
common-cpu = ["gemm", "rayon"]
nvidia-gpu = ["cuda", "cublas", "nccl", "libloading"]
cambricon-mlu = ["cndrv", "cnnl"]
ascend-card = ["ascendcl"]

[dependencies]
common.path = "../common"
digit-layout.workspace = true
half = "2.4"
rand = "0.8"
log = "0.4"

gemm = { version = "0.18", optional = true }
rayon = { version = "1.10", optional = true }

cuda = { workspace = true, optional = true }
cublas = { workspace = true, optional = true }
nccl = { workspace = true, optional = true }
libloading = { version = "0.8", optional = true }

cndrv = { workspace = true, optional = true }
cnnl = { workspace = true, optional = true }

ascendcl = { workspace = true, optional = true }

[build-dependencies]
build-script-cfg.workspace = true
search-cuda-tools.workspace = true
search-neuware-tools.workspace = true
search-ascend-tools.workspace = true
