[package]
name = "operators"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[features]
default = ["common-cpu", "nvidia-gpu"]
common-cpu = []
nvidia-gpu = ["cuda", "cublas", "nccl"]

[dependencies]
half = "2.4"
log = "0.4"
cuda = { git = "https://github.com/YdrMaster/cuda-driver", rev = "a4b3cf5", optional = true }
cublas = { git = "https://github.com/YdrMaster/cuda-driver", rev = "a4b3cf5", optional = true }
nccl = { git = "https://github.com/YdrMaster/cuda-driver", rev = "a4b3cf5", optional = true }

[build-dependencies]
build-script-cfg = "0.0"
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "a4b3cf5" }
