[package]
name = "operators"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[features]
default = ["common-cpu", "nv-gpu"]
common-cpu = []
nv-gpu = []

[dependencies]
half = "2.4"
