[package]
name = "operators"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[features]
default = ["common-cpu", "nvidia-gpu"]
common-cpu = ["gemm"]
nvidia-gpu = ["cuda", "cublas"]

[dependencies]
common = { path = "../common" }
digit-layout.workspace = true
half = "2.4"
log = "0.4"

gemm = { version = "0.18", optional = true }

cuda = { workspace = true, optional = true }
cublas = { workspace = true, optional = true }

[build-dependencies]
build-script-cfg.workspace = true
search-cuda-tools.workspace = true
search-neuware-tools.workspace = true
